data_dir: /../../../datasets/sleep_detection_dataset
processed_dir: /notebooks/kaggle-child-mind-institute-detect-sleep-states/data/processed_data
output_dir: /notebooks/kaggle-child-mind-institute-detect-sleep-states/data/output
model_dir: /notebooks/kaggle-child-mind-institute-detect-sleep-states/data/output/train
sub_dir: ./